/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubestahap1;

import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fujitsu
 */
public class GUI3 extends javax.swing.JFrame {
    
      DefaultListModel lm;
    Database db=new Database();
    acount active;
    message_database db_pesan ;
    /**
     
     */
    public GUI3(acount acc) {
        this.active=acc;
        initComponents();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonsendmessageg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textmessageg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textchattingg = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idgroupchatted = new javax.swing.JLabel();
        idaccounttogroup = new javax.swing.JLabel();
        textgroupchatted = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listfriendinvitegroup = new javax.swing.JList();
        textnamainvitegroup = new javax.swing.JTextField();
        buttonsearchinvitegroup = new javax.swing.JButton();
        buttoninvitegroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        buttonsendmessageg.setText(">>");
        buttonsendmessageg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsendmessagegActionPerformed(evt);
            }
        });

        textmessageg.setColumns(20);
        textmessageg.setRows(3);
        jScrollPane2.setViewportView(textmessageg);

        jLabel1.setText("Send Messages");

        textchattingg.setColumns(20);
        textchattingg.setRows(5);
        jScrollPane1.setViewportView(textchattingg);

        jButton1.setText("Invite member ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Group profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        idgroupchatted.setText("ID");

        idaccounttogroup.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idgroupchatted, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idaccounttogroup, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textgroupchatted, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(buttonsendmessageg))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idgroupchatted, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idaccounttogroup))
                .addGap(18, 18, 18)
                .addComponent(textgroupchatted, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)
                    .addComponent(buttonsendmessageg)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel2, "card2");

        jLabel5.setText("Invite Member Group");

        jLabel6.setText("Nama");

        listfriendinvitegroup.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listfriendinvitegroup);

        buttonsearchinvitegroup.setText("Search");
        buttonsearchinvitegroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsearchinvitegroupActionPerformed(evt);
            }
        });

        buttoninvitegroup.setText("aaInvite");
        buttoninvitegroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoninvitegroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(textnamainvitegroup))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonsearchinvitegroup, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttoninvitegroup, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textnamainvitegroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(buttonsearchinvitegroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttoninvitegroup)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "invitemembermenu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GUIprofile guiprofile= new GUIprofile();
        guiprofile.profileidgroup.setText(idgroupchatted.getText());
        CardLayout c = (CardLayout) guiprofile.profileswitch.getLayout();
        c.show(guiprofile.profileswitch,"profilegroup");
        guiprofile.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout c=(CardLayout) getContentPane().getLayout();
        c.show(getContentPane(), "invitemembermenu");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonsearchinvitegroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsearchinvitegroupActionPerformed
        db.connect();
        String namafriendinvite=textnamainvitegroup.getText();
        lm = new DefaultListModel();
        System.out.println(namafriendinvite+active.getUsername());
        try{
            if(! namafriendinvite.equals(""))
            {

                String query="select id_account,nama,username from account join log_friend where (log_friend.id_account1='"+active.getIdacount()+"' && account.id_account=log_friend.id_account2)|| (log_friend.id_account2='"+active.getIdacount()+"'&& account.id_account=log_friend.id_account1 )";
                ResultSet rs=db.getData(query);
                try {
                    while(rs.next())
                    {
                        int id_account_f=rs.getInt("id_account");
                        String nama_f=rs.getString("nama");
                        String username_f=rs.getString("username");
                        lm.addElement(id_account_f+"/"+nama_f);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(GUI3.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                throw new Exception ("Nama tidak boleh kosong");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "query gagal");
        }

        listfriendinvitegroup.setModel(lm);
        db.close();
    }//GEN-LAST:event_buttonsearchinvitegroupActionPerformed

    private void buttoninvitegroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoninvitegroupActionPerformed
        db.connect();
        try{
            String listvalue=listfriendinvitegroup.getSelectedValue().toString();
            String[] getlistvalue=listvalue.split("/");

            int idaccount_invited= Integer.parseInt(getlistvalue[0]);
            String query= "INSERT INTO `log_join_member`(`id_group`, `time_log_join`, `id_account`, `status_join`) VALUES ("+idgroupchatted.getText() +",now(),'"+idaccount_invited+"',false)";
            System.out.println(query);
            
            int i=db.execute(query);
            if(i>0)
            {
                JOptionPane.showMessageDialog(this, "Requesting success... Waitin for approve");
            }
            else
            {
                throw new Exception ("Query gagal");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        db.close();
    }//GEN-LAST:event_buttoninvitegroupActionPerformed

    private void buttonsendmessagegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsendmessagegActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_buttonsendmessagegActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoninvitegroup;
    private javax.swing.JButton buttonsearchinvitegroup;
    private javax.swing.JButton buttonsendmessageg;
    public static javax.swing.JLabel idaccounttogroup;
    public static javax.swing.JLabel idgroupchatted;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList listfriendinvitegroup;
    private javax.swing.JTextArea textchattingg;
    public static javax.swing.JLabel textgroupchatted;
    private javax.swing.JTextArea textmessageg;
    private javax.swing.JTextField textnamainvitegroup;
    // End of variables declaration//GEN-END:variables
}
